# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.2
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongo:/data/db:cached
    ports:
      - 27017:27017
    # default port is 27017

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 9001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  minio:
    image: minio/minio:RELEASE.2020-06-01T17-28-03Z
    restart: always
    entrypoint: sh
    command: -c 'mkdir -p /data/dreamshiplocal && /usr/bin/minio server /data'
    environment:
      MINIO_ACCESS_KEY: 2QnjrZa8xskGDkgRHa
      MINIO_SECRET_KEY: svyY54BZL4curtbPX2
    volumes:
      - ./data/minio:/data:cached
    ports:
      - 9002:9000